default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: parn_academy_quest_development

test:
  <<: *default
  database: parn_academy_quest_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_production
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *primary_production
    url: <%= ENV["DATABASE_URL"] %>
